amovie_async@Ring0,volume=precision=fixed,volume@VolRing0=precision=fixed[a0],
amovie_async@Ring1,volume=precision=fixed,volume@VolRing1=precision=fixed[a1],
amovie_async@Music0=fflags=+discardcorrupt:ignore_editlist=1:indexmem=32768:reconnect=1:reconnect_delay_max=3:rw_timeout=2000000,volume=precision=fixed,volume@VolMusic0=precision=fixed[a2],
amovie_async@Music1=indexmem=32768:reconnect=1:reconnect_delay_max=3:rw_timeout=2000000,volume=precision=fixed,volume@VolMusic1=precision=fixed[a3],
amovie_async@Music2=indexmem=32768:reconnect=1:reconnect_delay_max=3:rw_timeout=2000000,volume=precision=fixed,volume@VolMusic2=precision=fixed[a4],
amovie_async@Music3=indexmem=32768:reconnect=1:reconnect_delay_max=3:rw_timeout=2000000,volume=precision=fixed,volume@VolMusic3=precision=fixed[a5],
amovie_async@Alarm0,volume=precision=fixed,volume@VolAlarm0=precision=fixed[a6],
movie_async@Video0[v0a][v0v],
[v0v]devsink@vsink0=format=fbdev:devname=/dev/fb0,
[v0a]afade,volume=precision=fixed,volume@VolMedia0=precision=fixed[a7],
movie_async@Video1=datqmax=1:analyzeduration=40[v1a][v1v],
[v1v]devsink@vsink1=format=vtun:server_path=Vtun_Video1:pixel_fmt=28:frame_count=3,
[v1a]afade,volume=precision=fixed,volume@VolMedia1=precision=fixed[a8],
adevsrc@a2dpsnk=format=bluelet:devname=default:server_name=local,volume@VolA2dpsnk=precision=fixed[a9],
[a0][a1][a2][a3][a4][a5][a6][a7][a8][a9]amix=inputs=10:timeout=40:first_input=8:dropout_transition=0.5[mix],
[mix]adevsink@pcm0p=format=nuttx:sample_rate=44100:ch_layout=stereo:devname=/dev/audio/pcm0p;
adevsrc@pcm10c=format=nuttx:devname=/dev/audio/pcm0c[pcm10c],
[pcm10c]amoviesink_async@VOIPtx,
adevsrc@pcm11c=format=nuttx:devname=/dev/audio/pcm0c:period_time=10[pcm11c],
[pcm11c]amoviesink_async@WWEtx,
adevsrc@pcm12c=format=nuttx:devname=/dev/audio/pcm0c[pcm12c],
[pcm12c]amoviesink_async@MDStx
