abufsrc@Music0=outputs=2:map=1 0[Music0_0][Music0_1],

abufsrc@Music1=outputs=2:map=1 0[Music1_0][Music1_1],

abufsrc@Ring=outputs=2:map=1 0[Ring0][Ring1],

abufsrc@Media=outputs=2:map=1 0[Media0][Media1],

abufsrc@Alarm=outputs=2:map=1 0[Alarm0][Alarm1],

abufsrc@Sport=outputs=2:map=1 0[Sport0][Sport1],

abufsrc@Video=outputs=2:map=1 0[Video0][Video1],

abufsrc@Enforced=outputs=1:map=1[Enforced0],

abufsrc@netcomm=outputs=2:map=1 0[netcomm0][netcomm1],

abufsrc@TTS=outputs=2:map=1 0[TTS0][TTS1],

abufsrc@CallRing=outputs=2:map=1 0[CallRing0][CallRing1],

alsasrc@pcm0c=devname=pcm0c:outputs=4:map=1 0 0 0[cap0][cap1][cap2][cap3],

alsasrc@SCOrx=devname=pcm1c:outputs=4:map=0 0 0 0[SCOrx0][SCOrx1][SCOrx2][SCOrx3],

alsasrc@MDMrx=devname=pcm2c:outputs=2:map=0 0[MDMrx0][MDMrx1],

[Music0_0][Music1_0][Ring0][Alarm0][Sport0][Video0][Enforced0][SCOrx0][MDMrx0][netcomm0][Media0][TTS0][CallRing0]alsasink@pcm0p=inputs=13:devname=pcm0p,

[Music0_1][Music1_1][Ring1][Alarm1][Sport1][Video1][cap3][SCOrx3]tinycomprsink@a2dpsrc=inputs=8:devname=a2dpsrcp,

[cap1][MDMrx1][netcomm1][Media1][TTS1][CallRing1]alsasink@SCOtx=inputs=6:devname=pcm1p,

[cap2][SCOrx1]alsasink@MDMtx=inputs=2:devname=pcm2p,

[cap0][SCOrx2]abufsink@Capture=inputs=2
